SELECT * FROM TRADE_ITEM;

SELECT * FROM TRADE_LIST;

SELECT * FROM PUBLIC.TRADE_LIST_TO_TRADE_ITEM;


SELECT
	*
FROM
	TRADE_LIST tl
	INNER JOIN TRADE_LIST_TO_TRADE_ITEM tlti ON tlti.TRADE_LIST_ID = tl.TRADE_LIST_ID
	INNER JOIN TRADE_ITEM ti ON ti.TRADE_ITEM_ID = tlti.TRADE_ITEM_ID;